name: CI

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy: 
      fail-fast: false
      matrix:
        job:
          # - { os: ubuntu-latest  , target: arm-unknown-linux-gnueabihf }
          # - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu }
          - { os: macos-latest   , target: x86_64-apple-darwin }
          - { os: windows-latest , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.45.0 # minimum supported rust version
          target: ${{ matrix.job.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.job.target }}

  fmt-and-clippy:
    name: Rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
