name: release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy: 
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu }
          - { os: macos-latest   , target: x86_64-apple-darwin }
          - { os: windows-latest , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.45.0 # minimum supported rust version
          target: ${{ matrix.job.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.job.target }}
  
  build-on-arm-and-musl:
    name: Build on ARM and MUSL
    runs-on: ${{ matrix.job.os }}
    strategy: 
      matrix:
        job:
          - { os: ubuntu-latest , target: arm-unknown-linux-gnueabihf }
          - { os: ubuntu-latest , target: x86_64-unknown-linux-musl }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.45.0 # minimum supported rust version
          target: ${{ matrix.job.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build

  deploy:
    name: Deploy
    needs: [ build-on-arm-and-musl, test ]
    runs-on: ${{ matrix.job.os }}
    strategy: 
      matrix:
        job:
          - { os: ubuntu-latest  , target: arm-unknown-linux-gnueabihf , use-cross: true }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl   , use-cross: true }
          - { os: macos-latest   , target: x86_64-apple-darwin }
          - { os: windows-latest , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target ${{ matrix.job.target }}
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release          
          if [ "${{ matrix.job.os }}" = "windows-latest" ]; then
            7z a ../../../xh-${{ matrix.job.target }}.zip xh.exe
          elif [ "${{ matrix.job.os }}" = "macos-latest" ]; then
            zip ../../../xh-${{ matrix.job.target }}.zip xh
          else
            tar czvf ../../../xh-${{ matrix.job.target }}.tar.gz xh
          fi
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'xh*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
