name: release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  # We can't run tests using musl due to httpmock's dependency on OpenSSL
  # Let's check if it at least able to build.
  build-on-musl:
    name: Build using musl as target
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl

  test:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy: 
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: arm-unknown-linux-gnueabihf , use-cross: true }
          # uncomment this once isahc, one of httpmock dependencies, adds support for rustls
          # as a tls engine, see https://github.com/sagebind/isahc/issues/199
          # - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl   , use-cross: true }
          - { os: macos-latest   , target: x86_64-apple-darwin }
          - { os: windows-latest , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --target ${{ matrix.job.target }}

  deploy:
    name: Deploy
    needs: [ build-on-musl, test ]
    runs-on: ${{ matrix.job.os }}
    strategy: 
      matrix:
        job:
          - { os: ubuntu-latest  , target: arm-unknown-linux-gnueabihf , use-cross: true }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl   , use-cross: true }
          - { os: macos-latest   , target: x86_64-apple-darwin }
          - { os: windows-latest , target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v2
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target ${{ matrix.job.target }}
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release          
          if [ "${{ matrix.job.os }}" = "windows-latest" ]; then
            7z a ../../../xh-${{ matrix.job.target }}.zip xh.exe
          elif [ "${{ matrix.job.os }}" = "macos-latest" ]; then
            zip ../../../xh-${{ matrix.job.target }}.zip xh
          else
            tar czvf ../../../xh-${{ matrix.job.target }}.tar.gz xh
          fi
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'xh*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
